#!/usr/bin/python
import json
from subprocess import call

config_file = "/home/kcpclient/config.json"
json_data = open(config_file).read()
config = json.loads(json_data)

pen_command = "pen -f -r -x " + config["pen"]["max_connection"] + " 127.0.0.1:" + config["pen"]["port"]

i=1
while (i <= 5):
  kcp = "kcp" + str(i)
  if kcp in config:
    pen_command = pen_command + " 127.0.0.1:" +  config[kcp]["port"]
    kcp_command = "client_linux_amd64 -r " + config[kcp]["server_address"] + ":" + config[kcp]["server_port"] + " -l :" + config[kcp]["port"] + " -mode " + config[kcp]["mode"] + " --key " + config[kcp]["password"] + " " + config[kcp]["others"] + " &"
    call(kcp_command, shell=True)

  i = i + 1

call(pen_command, shell=True)